server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 500m;

    # Disable caching for HTML and JSON so updates are always picked up
    location ~* \.(html|json)$ {
        add_header Cache-Control "no-store";
    }

    location = /VERSION {
        alias /var/www/version/VERSION;
    }

    location /api/ {
        proxy_pass http://whisper:8080/;
        proxy_read_timeout 1800s;
        proxy_send_timeout 1800s;
    }
}
