services:
  whisper:
    image: ghcr.io/kth8/whisper-server-vulkan:${WHISPER_IMAGE_TAG:-latest}
    init: true
    devices:
      - /dev/kfd
      - /dev/dri
    read_only: true
    tmpfs:
      - /root/.cache/mesa_shader_cache
    ports:
      - "8080:8080"
    volumes:
      - ~/models:/models:ro
    restart: unless-stopped
